### ISSUE TITLE
Unable to load in Paper 1.20.2

### ISSUE THREAD

**Issue by liangcha385** [MrStudios/DeathRun#13]
### Module

Core (Standard Users)

### Plugin Version

v1.1.4

### Server Version

1.20.2

### Issue Details

I added all the dependencies, but it still cannot load properly

Server Plugins:  DeathRun, WorldEdit
WorldEdit Version: v7.2.19+6642-415ef95
This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
```
[18:38:04] [Server thread/INFO]: [DeathRun] Enabling DeathRun v1.1.4
[18:38:05] [Server thread/INFO]: [ProtocolSidebar] Server version: (MC: 1.20.2) (protocol 764)
[18:38:05] [Server thread/INFO]: [ProtocolSidebar] Please report any bugs to the developer: https://github.com/CatCoderr/ProtocolSidebar/issues
[18:38:06] [Server thread/ERROR]: Error occurred while enabling DeathRun v1.1.4 (Is it up to date?)
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, pl.mrstudios.deathrun.libraries.litecommands.annotations.command.Command
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at java.util.stream.SpinedBuffer.copyInto(SpinedBuffer.java:194) ~[?:?]
	at java.util.stream.Nodes$SpinedNodeBuilder.copyInto(Nodes.java:1290) ~[?:?]
	at java.util.stream.SpinedBuffer.asArray(SpinedBuffer.java:215) ~[?:?]
	at java.util.stream.Nodes$SpinedNodeBuilder.asArray(Nodes.java:1296) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:617) ~[?:?]
	at pl.mrstudios.deathrun.plugin.Bootstrap.onEnable(Bootstrap.java:138) ~[deathrun-core-1.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:38:06] [Server thread/INFO]: [DeathRun] Disabling DeathRun v1.1.4
```

### Confirmation

- [X] I agree to follow this project Contributing & Issues rules.

**Comment by SfenKer** [comment]
Resolved in #14
