### ISSUE TITLE
Injector Issue

### ISSUE THREAD

**Issue by ghost** [MrStudios/DeathRun#16]
### Module

Core (Standard Users)

### Plugin Version

1.2.0

### Server Version

1.20.4

### Issue Details

```[14:53:00 ERROR]: Error occurred while enabling DeathRun v1.2.0 (Is it up to date?)
pl.mrstudios.deathrun.libraries.commons-inject.exception.InjectConstructorException: Could not find any constructor annotated with @Inject in class pl.mrstudios.deathrun.libraries.litecommands.bukkit.TabCompletePaperAsync.
        at pl.mrstudios.deathrun.libraries.commons-inject.Injector.inject(Injector.java:24) ~[deathrun-core-1.2.0.jar:?]
        at pl.mrstudios.deathrun.plugin.Bootstrap.lambda$onEnable$2(Bootstrap.java:153) ~[deathrun-core-1.2.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at pl.mrstudios.deathrun.plugin.Bootstrap.onEnable(Bootstrap.java:153) ~[deathrun-core-1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-450]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-450]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-450]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
        








```

server version: git-Paper-450 (MC: 1.20.4)

### Confirmation

- [X] I agree to follow this project Contributing & Issues rules.

**Comment by SfenKer** [comment]
Resolved problem with listener registration, changes will be published into 1.2.1 hotfix.

**Comment by ghost** [comment]
The plugin runs with the hotfix version, however I am encountering an immediate client disconnect problem now. I'll make a new issue for it. Cheers.

**Comment by SfenKer** [comment]
this is caused because protocolsidebar is not supporting 1.20.4 yet

**Comment by ghost** [comment]
> this is caused because protocolsidebar is not supporting 1.20.4 yet

Ah, so a known issue. I won't make an issue then, but I hope support will be implemented soon
